name: Deploy prod (S3 + CloudFront)
on: { push: { branches: [ main ] } }
permissions: { id-token: write, contents: read }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync assets
        run: aws s3 sync assets s3://${{ secrets.S3_BUCKET_PROD }}/assets --delete --cache-control "public, max-age=31536000, immutable"
      - name: Upload HTML
        run: |
          for f in index.html admin.html architecture.html; do
            [ -f "$f" ] && aws s3 cp "$f" s3://${{ secrets.S3_BUCKET_PROD }}/$f \
              --metadata-directive REPLACE --cache-control "no-store, no-cache, must-revalidate" --content-type "text/html";
          done
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DIST_ID_PROD }} --paths "/" "/index.html" "/admin.html" "/architecture.html"
